name: Terraform Deploy & Destroy (Az-104-Lab)

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Terraform action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: Az-104-Lab

    env:
      LOCATION: eastus
      CONTAINER_NAME: tfstate

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6  # specify version, or remove to get latest

      # 3️⃣ Azure Login using Service Principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 4️⃣ Terraform Init
      - name: Terraform Init
        run: terraform init -input=false

      # 5️⃣ Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # 6️⃣ Terraform Apply if 'apply' selected
      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform apply -input=false -auto-approve tfplan

      # 7️⃣ Terraform Destroy if 'destroy' selected
      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: terraform destroy -auto-approve
