name: Terraform Deploy & Destroy (Az-104-Lab)

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Terraform action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: Az-104-Lab

    env:
      LOCATION: eastus
      CONTAINER_NAME: tfstate
      PREFIX: az104lab

    steps:
      # ------------------------------
      # 1️⃣ Checkout Repository
      # ------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ------------------------------
      # 2️⃣ Azure Login
      # ------------------------------
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ------------------------------
      # 3️⃣ Generate Backend Resource Names
      # ------------------------------
      - name: Generate Unique Resource Names
        id: names
        run: |
          RG_NAME="${{ env.PREFIX }}-tfstate-rg"
