name: Terraform Deploy & Destroy (Az-104-Lab)

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Terraform action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: Az-104-Lab

    env:
      LOCATION: eastus
      CONTAINER_NAME: tfstate
      PREFIX: az104lab
      RG_NAME: az104lab-tfstate-rg
      STORAGE_NAME: yourstorageaccountname   # Replace this with your real storage account name

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Install Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.7'  # specify your desired version

      # 3️⃣ Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 4️⃣ Terraform Init (reconfigure backend)
      - name: Terraform Init
        run: |
          terraform init -reconfigure \
            -backend-config="resource_group_name=${RG_NAME}" \
            -backend-config="storage_account_name=${STORAGE_NAME}" \
            -backend-config="container_name=${CONTAINER_NAME}" \
            -backend-config="key=terraform.tfstate"

      # 5️⃣ Terraform Plan & Apply or Destroy based on input
      - name: Terraform Plan & Apply
        if: github.event.inputs.action == 'apply'
        run: |
          terraform plan
          terraform apply -auto-approve

      - name: Terraform Plan & Destroy
        if: github.event.inputs.action == 'destroy'
        run: |
          terraform plan -destroy
          terraform destroy -auto-approve

      # 6️⃣ Output Public IP and Resource Group (optional)
      - name: Show outputs
        if: github.event.inputs.action == 'apply'
        run: |
          terraform output vm_public_ip
          terraform output resource_group
