name: Terraform Deploy & Destroy (Az-104-Lab)

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Terraform action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: Az-104-Lab  # adjust this if your Terraform files are in a different folder

    env:
      LOCATION: eastus           # your default location
      CONTAINER_NAME: tfstate    # must match backend.tf container_name

    steps:
      # 1. Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Azure login using Service Principal stored in GitHub Secrets
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Terraform Init (uses backend.tf for backend config)
      - name: Terraform Init
        run: terraform init -input=false

      # 4. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # 5. Terraform Apply (only if action is 'apply')
      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -input=false -auto-approve tfplan

      # 6. Terraform Destroy (only if action is 'destroy')
      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
