name: Terraform Deploy & Destroy (Az-104-Lab with Remote Backend)

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Terraform action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      LOCATION: "eastus"

    steps:
    # STEP 1 - Checkout
    - name: Checkout repository
      uses: actions/checkout@v4

    # STEP 2 - Azure Login
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # STEP 3 - Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.5

    # STEP 4 - Terraform Init
    - name: Terraform Init
      working-directory: ..
      env:
        ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
        ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
        ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
        ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
      run: terraform init -reconfigure

    # STEP 5 - Terraform Plan
    - name: Terraform Plan
      if: ${{ github.event.inputs.action == 'apply' }}
      working-directory: ..
      run: terraform plan

    # STEP 6 - Terraform Apply
    - name: Terraform Apply
      if: ${{ github.event.inputs.action == 'apply' }}
      working-directory: ..
      run: terraform apply -auto-approve

    # STEP 7 - Terraform Destroy
    - name: Terraform Destroy
      if: ${{ github.event.inputs.action == 'destroy' }}
      working-directory: ..
      run: terraform destroy -auto-approve
