name: Terraform Deploy & Destroy (Az-104-Lab)

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Terraform action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: Az-104-Lab

    env:
      LOCATION: eastus
      CONTAINER_NAME: tfstate
      PREFIX: az104lab
      RG_NAME: az104lab-tfstate-rg
      STORAGE_NAME: yourstorageaccountname  # <-- Replace with your actual storage account name

      # Pass SP credentials to Terraform
      ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
      ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
      ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
      ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.7'  # or your preferred version

      - name: Terraform Init
        run: |
          terraform init -reconfigure \
            -backend-config="resource_group_name=${RG_NAME}" \
            -backend-config="storage_account_name=${STORAGE_NAME}" \
            -backend-config="container_name=${CONTAINER_NAME}" \
            -backend-config="key=terraform.tfstate"

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply or Destroy
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
